name: Github Pages Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'bitcoinzkio/bitcoinzk-home'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install and build
        run: pnpm install && pnpm build  

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: bitcoinzk.io
